global_costmap:
   global_frame: /map
   robot_base_frame: /base_link
   update_frequency: 15.0
   publish_frequency: 0
   static_map: true
   rolling_window: false
   resolution: 0.05
   transform_tolerance: 1.5
   map_type: costmap

GlobalPlanner:        
   allow_unknown: false 
